import { Plant } from './types';

export const PLANTS: Plant[] = [
  {
    id: 'rice',
    name: 'Rice',
    scientificName: 'Oryza sativa',
    season: 'Autumn/Summer',
    difficulty: 'moderate',
    type: 'grain',
    watering: 'High',
    sunlight: 'Direct Sun',
    soilPh: '5.5 - 6.5',
    diseases: ['Blast', 'Blight', 'Stem Borer'],
    companionPlants: ['Soybean', 'Azolla'],
    image: 'https://picsum.photos/seed/rice/400/300',
    description: 'A staple food for more than half of the worlds population.'
  },
  {
    id: 'tomato',
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    season: 'Year round',
    difficulty: 'easy',
    type: 'vegetable',
    watering: 'Medium',
    sunlight: 'Full Sun',
    soilPh: '6.0 - 6.8',
    diseases: ['Early Blight', 'Late Blight', 'Leaf Mold'],
    companionPlants: ['Basil', 'Marigold', 'Onion'],
    image: 'https://picsum.photos/seed/tomato/400/300',
    description: 'Versatile and popular garden vegetable.'
  },
  {
    id: 'mango',
    name: 'Mango',
    scientificName: 'Mangifera indica',
    season: 'Summer',
    difficulty: 'hard',
    type: 'fruit',
    watering: 'Medium',
    sunlight: 'Intense Sun',
    soilPh: '5.5 - 7.5',
    diseases: ['Anthracnose', 'Powdery Mildew'],
    companionPlants: ['Guava', 'Banana'],
    image: 'https://picsum.photos/seed/mango/400/300',
    description: 'The king of fruits, popular in South Asia.'
  },
  {
    id: 'chili',
    name: 'Chili Pepper',
    scientificName: 'Capsicum annuum',
    season: 'Monsoon/Winter',
    difficulty: 'easy',
    type: 'vegetable',
    watering: 'Moderate',
    sunlight: 'Full Sun',
    soilPh: '6.0 - 7.0',
    diseases: ['Damping off', 'Anthracnose', 'Leaf Curl'],
    companionPlants: ['Tomato', 'Basil'],
    image: 'https://picsum.photos/seed/chili/400/300',
    description: 'Used for spice and heat in various cuisines.'
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    season: 'Summer',
    difficulty: 'easy',
    type: 'vegetable',
    watering: 'High',
    sunlight: 'Partial Sun',
    soilPh: '6.0 - 7.0',
    diseases: ['Powdery Mildew', 'Mosaic Virus'],
    companionPlants: ['Corn', 'Bean', 'Peas'],
    image: 'https://picsum.photos/seed/cucumber/400/300',
    description: 'Refreshing and fast-growing climbing plant.'
  },
  {
    id: 'potato',
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    season: 'Winter',
    difficulty: 'moderate',
    type: 'vegetable',
    watering: 'Moderate',
    sunlight: 'Full Sun',
    soilPh: '5.0 - 6.0',
    diseases: ['Late Blight', 'Common Scab'],
    companionPlants: ['Marigold', 'Corn'],
    image: 'https://picsum.photos/seed/potato/400/300',
    description: 'Underground tuberous crop, essential for global food security.'
  }
];

export const CALENDAR_DATA: any[] = [
  { month: 0, crop: 'Rice', task: 'Boro season: Prepare seedling nursery and soil pilling.', type: 'sow', care: 'Keep water level low at first.' },
  { month: 0, crop: 'Potato', task: 'Monitor for Late Blight due to foggy mornings.', type: 'pest-alert', care: 'Apply preventative fungicide.' },
  { month: 1, crop: 'Rice', task: 'Transplant seedlings and ensure primary irrigation.', type: 'transplant', care: 'Maintain 2-3cm water layer.' },
  { month: 1, crop: 'Tomato', task: 'Harvest early winter crops.', type: 'harvest' },
  { month: 2, crop: 'Mango', task: 'Flowering stage: Apply hopper control protocols.', type: 'pest-alert', care: 'Avoid irrigation during full bloom.' },
  { month: 2, crop: 'Tomato', task: 'Apply organic fertilizer and basal mulch.', type: 'fertilize' },
  { month: 3, crop: 'Mango', task: 'Fruit setting: Start regular hydration cycles.', type: 'irrigate' },
  { month: 4, crop: 'Chili', task: 'Sow Kharif-I seeds in well-drained trays.', type: 'sow', care: 'Use organic seed treatment.' },
  { month: 5, crop: 'Rice', task: 'Aus season: Direct sowing of upland varieties.', type: 'sow' },
  { month: 5, crop: 'Jute', task: 'Intercultural operations and thinning.', type: 'prune' },
  { month: 6, crop: 'Rice', task: 'Harvest Boro crops in sunny windows.', type: 'harvest' },
  { month: 7, crop: 'Rice', task: 'Aman season: Seedbed preparation with compost.', type: 'sow' },
  { month: 8, crop: 'Rice', task: 'Transplant Aman seedlings amid monsoon rains.', type: 'transplant' },
  { month: 9, crop: 'Mango', task: 'Post-harvest pruning and nutrient loading.', type: 'prune' },
  { month: 10, crop: 'Vegetables', task: 'Sow winter vegetables (Rabi season).', type: 'sow', care: 'Protect from excess heat.' },
  { month: 11, crop: 'Potato', task: 'Planting of main season tubers.', type: 'sow', care: 'Use certified seed tubers.' },
];
